---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygrowatt-deployment
  namespace: default
  labels:
    app: pygrowatt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pygrowatt
  template:
    metadata:
      name: pygrowatt
      labels:
        app: pygrowatt
    spec:
      volumes:
        - name: pygrowatt-config
          secret:
            secretName: pygrowatt-config
            items:
            - key: config.ini
              path: config.ini
      containers:
      - name: pygrowatt-container
        image: pygrowatt
        env:
          - name: TZ
            value: Etc/GMT
        ports:
        - containerPort: 5279
          protocol: TCP
        volumeMounts:
          - mountPath: "/opt/PyGrowatt/scripts/config.ini"
            subPath: "config.ini"
            name: pygrowatt-config
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: pygrowatt-service
  namespace: default
spec:
  selector:
    app: pygrowatt
  ports:
    - port: 5279
      targetPort: 5279
  type: LoadBalancer